---
- name: httpd installation
  hosts: localhost
  tasks:
   - name: install httpd
     yum:
      name: httpd
      state: present
   - name: restart httpd
     service:
      name: httpd
      state: started

